# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [9]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [10]:
# Create a 1-dimensional NumPy array using np.array()

arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

# Create a 2-dimensional NumPy array using np.array()

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

# Create a 3-dimensional Numpy array using np.array()

# Create a 3-dimensional NumPy array (a 3D array)
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
print(arr3d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [11]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
shape = arr1d.shape
num_dimensions = arr1d.ndim
data_type = arr1d.dtype
array_size = arr1d.size
array_type = type(arr1d)

print("Shape:", shape)              
print("Number of Dimensions:", num_dimensions)  
print("Data Type:", data_type)     
print("Size:", array_size)         
print("Type of Array:", array_type) 

Shape: (5,)
Number of Dimensions: 1
Data Type: int32
Size: 5
Type of Array: <class 'numpy.ndarray'>


In [12]:
# Attributes of 2-dimensional array
shape = arr2d.shape
num_dimensions = arr2d.ndim
data_type = arr2d.dtype
array_size = arr2d.size
array_type = type(arr2d)

print("Shape:", shape)              
print("Number of Dimensions:", num_dimensions)  
print("Data Type:", data_type)     
print("Size:", array_size)         
print("Type of Array:", array_type) 

Shape: (3, 3)
Number of Dimensions: 2
Data Type: int32
Size: 9
Type of Array: <class 'numpy.ndarray'>


In [13]:
# Attributes of 3-dimensional array
shape = arr3d.shape
num_dimensions = arr3d.ndim
data_type = arr3d.dtype
array_size = arr3d.size
array_type = type(arr3d)

print("Shape:", shape)              
print("Number of Dimensions:", num_dimensions)  
print("Data Type:", data_type)     
print("Size:", array_size)         
print("Type of Array:", array_type) 

Shape: (3, 2, 3)
Number of Dimensions: 3
Data Type: int32
Size: 18
Type of Array: <class 'numpy.ndarray'>


In [59]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

# Create a DataFrame from the 1D array
df = pd.DataFrame(arr1d, columns=['Column_arr1'])

# Display the DataFrame
print(df)


   Column_arr1
0            1
1            2
2            3
3            4
4            5


In [60]:
# Create an array of shape (10, 2) with only ones

ones_array_10_2 = np.ones((10, 2))

# Print the resulting array
print(ones_array_10_2)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [62]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array =  np.zeros((7,2,3))
print(zeros_array)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [63]:
# Create an array within a range of 0 and 100 with step 3
array_with_step = np.arange(0, 100, 3)

print(array_with_step)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [65]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_7_2 = np.random.rand(7, 2) * 10

print(random_array_7_2)

random_integer_array = np.random.randint(0, 11, size=(7, 2))

print(random_integer_array)

[[5.90240356 5.0783094 ]
 [1.2957757  2.85985921]
 [0.66351791 0.21243589]
 [6.44784317 0.44967523]
 [5.30144325 3.12917733]
 [4.17636971 9.64522437]
 [7.70817882 8.12429671]]
[[5 6]
 [1 6]
 [1 7]
 [9 4]
 [6 9]
 [4 5]
 [8 7]]


In [66]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.rand(3, 5)

print(random_float_array)

[[0.51669921 0.18060106 0.77870542 0.76382721 0.17442971]
 [0.32870271 0.99573177 0.26825257 0.80210928 0.30882428]
 [0.20787102 0.23982912 0.89817582 0.84237695 0.94516717]]


In [71]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

random_array_4_6 = np.random.randint(0, 11, size=(4, 6))

print(random_array_4_6)


[[ 6  3 10  7  4  6]
 [ 9  2  6 10 10  7]
 [ 4  3  7  7  2  5]
 [ 4  1  7  5  1  4]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?



A:the same random numbers in the array. The reason for this is that setting the random seed initializes the pseudorandom number generator (PRNG) in a way that it produces the same sequence of random numbers every time you use that seed.

In [74]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_3_7 = np.random.randint(1, 11, size=(3, 7))

# Print the random array
print("Random Array:")
print(random_array_3_7)

# Find the unique numbers in the array you just created
unique_numbers = np.unique(random_array_3_7)

# Print the unique numbers
print("Unique Numbers:")
print(unique_numbers)



Random Array:
[[10  2 10  4  8  7  9]
 [ 8  5  2  5  8 10  9]
 [ 9  1  9  7  9  8  1]]
Unique Numbers:
[ 1  2  4  5  7  8  9 10]


In [77]:
# Find the 0'th index of the latest array you created
zeros_index = random_array_3_7[0]
element_at_index_0 = unique_numbers[0]
print(" 0'th index:", zeros_index)
print("Element at 0'th index:", element_at_index_0)

 0'th index: [10  2 10  4  8  7  9]
Element at 0'th index: 1


In [79]:
# Get the first 2 rows of latest array you created
first_two_rows = random_array_3_7[:2]

# Print the result
print("First two rows of the array")
print(first_two_rows)

First two rows of the array
[[10  2 10  4  8  7  9]
 [ 8  5  2  5  8 10  9]]


In [81]:
# Get the first 2 values of the first 2 rows of the latest array
first_two_rows_values = random_array_3_7[:2, :2]

# Print the result
print("First two values of the first two rows:")
print(first_two_rows_values)

First two values of the first two rows:
[[10  2]
 [ 8  5]]


In [82]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array_3_5= np.random.randint(0, 11, size=(3, 5))

# Create an array of ones of the same size (3, 5)
ones_array_3_5= np.ones((3, 5))

print("Random Array:")
print(random_array_3_5)

print("Ones Array:")
print(ones_array_3_5)


Random Array:
[[ 7  7 10  2  0]
 [ 7  2  2  0 10]
 [ 4  9  6  9  8]]
Ones Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [83]:
# Add the two arrays together
result_array = random_array_3_5 + ones_array_3_5
print(result_array)

[[ 8.  8. 11.  3.  1.]
 [ 8.  3.  3.  1. 11.]
 [ 5. 10.  7. 10.  9.]]


In [85]:
# Create another array of ones of shape (5, 3)
ones_array_5_3 = np.ones((5,3))
print(ones_array_5_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [86]:
# Try add the array of ones and the other most recent array together
result_array  = random_array_3_5 + ones_array_5_3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

A: error becuase of shapes , fix it using reshape of array


In [87]:
# Create another array of ones of shape (3, 5)
ones_array_3_5= np.ones((3, 5))


In [89]:
# Subtract the new array of ones from the other most recent array
subtracted_array = random_array_3_5 - ones_array_3_5
print(subtracted_array)

[[ 6.  6.  9.  1. -1.]
 [ 6.  1.  1. -1.  9.]
 [ 3.  8.  5.  8.  7.]]


In [90]:
# Multiply the ones array with the latest array
multiplicated_array = subtracted_array  * ones_array_3_5
print(multiplicated_array)

[[ 6.  6.  9.  1. -1.]
 [ 6.  1.  1. -1.  9.]
 [ 3.  8.  5.  8.  7.]]


In [91]:
# Take the latest array to the power of 2 using '**'
squared_array = multiplicated_array ** 2
print(squared_array)

[[36. 36. 81.  1.  1.]
 [36.  1.  1.  1. 81.]
 [ 9. 64. 25. 64. 49.]]


In [92]:
# Do the same thing with np.square()
squared_array2= np.square(multiplicated_array)
print(squared_array2)

[[36. 36. 81.  1.  1.]
 [36.  1.  1.  1. 81.]
 [ 9. 64. 25. 64. 49.]]


In [93]:
# Find the mean of the latest array using np.mean()
mean_value = np.mean(squared_array)

# Print the mean
print("Mean of the array (squared_array):", mean_value)

Mean of the array (squared_array): 32.4


In [95]:
# Find the maximum of the latest array using np.max()
max_value = np.max(squared_array)

# Print the max
print("Max of the array (squared_array):", max_value)

Max of the array (squared_array): 81.0


In [97]:
# Find the minimum of the latest array using np.min()
min_value = np.min(squared_array)

# Print the min
print("Min of the array (squared_array):", min_value)

Min of the array (squared_array): 1.0


In [98]:
# Find the standard deviation of the latest array
std_deviation = np.std(squared_array)

# Print the standard deviation
print("Standard Deviation of the array (squared_array):", std_deviation)

Standard Deviation of the array (squared_array): 28.945465966192355


In [99]:
# Find the variance of the latest array
variance = np.var(squared_array)

# Print the variance
print("Variance of the array (squared_array):", variance)

Variance of the array (squared_array): 837.8399999999999


In [100]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = squared_array.reshape(3, 5, 1)

# Print the reshaped array
print("Reshaped Array (3, 5, 1):")
print(reshaped_array)

Reshaped Array (3, 5, 1):
[[[36.]
  [36.]
  [81.]
  [ 1.]
  [ 1.]]

 [[36.]
  [ 1.]
  [ 1.]
  [ 1.]
  [81.]]

 [[ 9.]
  [64.]
  [25.]
  [64.]
  [49.]]]


In [101]:
# Transpose the latest array
transposed_array = reshaped_array.T

# Print the transposed array
print("Transposed Array:")
print(transposed_array)

Transposed Array:
[[[36. 36.  9.]
  [36.  1. 64.]
  [81.  1. 25.]
  [ 1.  1. 64.]
  [ 1. 81. 49.]]]


What does the transpose do?

A: operation that switches the rows and columns of the original matrix

In [102]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array_3_3 = np.random.randint(0, 11, size=(3, 3))

random_array_3_2 = np.random.randint(0, 11, size=(3, 2))

print(random_array_3_3)

print(random_array_3_2)

[[6 8 7]
 [1 0 6]
 [6 7 4]]
[[ 2  7]
 [ 5 10]
 [ 2  0]]


In [103]:
# Perform a dot product on the two newest arrays you created

dot_product_result = np.dot(random_array_3_3, random_array_3_2)

# Print the dot product result
print("Dot Product Result:")
print(dot_product_result)

Dot Product Result:
[[ 66 122]
 [ 14   7]
 [ 55 112]]


In [104]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_4_3 = np.random.randint(0, 11, size=(4, 3))

random_array_4_3_second = np.random.randint(0, 11, size=(4, 3))

print(random_array_4_3)

print(random_array_4_3_second)

[[ 2  4  2]
 [ 0  4  9]
 [ 6  6 10]
 [ 8  9  9]]
[[ 2  6  0]
 [ 3  3  4]
 [ 6  6 10]
 [ 3  6 10]]


In [106]:
# Perform a dot product on the two newest arrays you created

dot_product_result2 = np.dot(random_array_4_3, random_array_4_3_second)

# Print the dot product result
print("Dot Product Result:")
print(dot_product_result2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [111]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
transposed_random_array_4_3 = random_array_4_3.T
dot_product_result2 = np.dot(transposed_random_array_4_3, random_array_4_3_second)

# Print the dot product result
print("Dot Product Result:")
print(dot_product_result2)

Dot Product Result:
[[ 64  96 140]
 [ 83 126 166]
 [118 153 226]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [114]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(0, 11, size=(3, 3))
array2 = np.random.randint(0, 11, size=(3, 3))
print(array1)
print(array2)

[[ 3  8  2]
 [ 6  5  7]
 [10  8  4]]
[[ 0  2  9]
 [ 7 10  5]
 [ 7  8  3]]


In [115]:
# Compare the two arrays with '>'
comparison_result = array1 > array2

# Print the result of the comparison
print("Comparison Result (array1 > array2):")
print(comparison_result)

Comparison Result (array1 > array2):
[[ True  True False]
 [False False  True]
 [ True False  True]]


What happens when you compare the arrays with `>`?

A:check if one array's elements are greater than the corresponding elements in the other array, 

In [116]:
# Compare the two arrays with '>='
comparison_result = array1 >= array2

# Print the result of the comparison
print("Comparison Result (array1 >= array2):")
print(comparison_result)

Comparison Result (array1 >= array2):
[[ True  True False]
 [False False  True]
 [ True  True  True]]


In [117]:
# Find which elements of the first array are greater than 7
elements_greater_than_7 = array1 > 7

# Print the result
print("Elements of the first array greater than 7:")
print(elements_greater_than_7)

Elements of the first array greater than 7:
[[False  True False]
 [False False False]
 [ True  True False]]


In [118]:
# Which parts of each array are equal? (try using '==')
equal_elements = array1 == array2

# Print the result
print("Equal Elements (array1 == array2):")
print(equal_elements)

Equal Elements (array1 == array2):
[[False False False]
 [False False False]
 [False  True False]]


In [119]:
# Sort one of the arrays you just created in ascending order
sorted_array = np.sort(array1)

# Print the sorted array
print("Sorted Array in Ascending Order:")
print(sorted_array)

Sorted Array in Ascending Order:
[[ 2  3  8]
 [ 5  6  7]
 [ 4  8 10]]


In [120]:
# Sort the indexes of one of the arrays you just created
sorted_indices = np.argsort(array1, axis=None)

# Print the sorted indices
print("Sorted Indices:")
print(sorted_indices)

Sorted Indices:
[2 0 8 4 3 5 1 7 6]


In [122]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(array1)
# Print the maximum index
print("Index with Maximum Value:", max_index)


Index with Maximum Value: 6


In [123]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(array1)
# Print the minimm index
print("Index with Minimum Value:", min_index)


Index with Minimum Value: 2


In [125]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indices_axis1 = np.argmax(array1, axis=1)

# Print the maximum indices along the first axis
print("Indices with Maximum Values along Axis 1:")
print(max_indices_axis1)

Indices with Maximum Values along Axis 1:
[1 2 0]


In [126]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indices_axis0= np.argmin(array1, axis=0)

# Print the maximum indices along the first axis
print("Indices with Minimum Values along Axis 1:")
print(min_indices_axis0)

Indices with Minimum Values along Axis 1:
[0 1 0]


In [127]:
# Create an array of normally distributed random numbers
mean = 0  # Mean of the normal distribution
std_dev = 1  # Standard deviation of the normal distribution
size = (3, 3)  # Shape of the array

# Generate the array of normally distributed random numbers
normal_array = np.random.normal(mean, std_dev, size)

# Print the array
print("Array of Normally Distributed Random Numbers:")
print(normal_array)

Array of Normally Distributed Random Numbers:
[[ 0.25755039 -0.07444592 -1.91877122]
 [-0.02651388  0.06023021  2.46324211]
 [-0.19236096  0.30154734 -0.03471177]]


In [128]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)

# Print the array
print("Evenly Spaced Array between 1 and 100:")
print(evenly_spaced_array)

Evenly Spaced Array between 1 and 100:
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.